version: '3.9'

services: 
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      MSSQL_SA_PASSWORD: "Teste123!"
      ACCEPT_EULA: 1
      MSSQL_PID: "Developer"
    ports:
      - "14330:1433"
    networks:
      - hackaton_network
    volumes:
      - sqlserver_data:/var/opt/mssql

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./scripts:/scripts
    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 40s
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U SA -P Teste123! -d master -i ./scripts/generate-database.sql
    networks:
      - hackaton_network
  
  hackaton-api:
    image: ghcr.io/fiap-pos-tech-4nett-grupo-31/hackaton:latest
    container_name: hackaton-api
    ports:
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=AgendaMedica;User Id=SA;Password=Teste123!;TrustServerCertificate=True
    restart: always
    networks:
      - hackaton_network


volumes:
  sqlserver_data:
    driver: local

networks:
  hackaton_network: