name: Build & Deploy WebAPI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./WebAPI/

    - name: Build
      run: dotnet build -c Release --no-restore
      working-directory: ./WebAPI/

    - name: Publish
      run: dotnet publish -c Release -o out --no-build
      working-directory: ./WebAPI/

    - name: Unit Test - Application.Unit.Tests
      run: dotnet test ./Application.Unit.Tests.csproj
      working-directory: ./Application.Unit.Tests/

    - name: Copy Dockerfile to publish folder
      run: cp WebAPI/Dockerfile WebAPI/out/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./WebAPI/out

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Aguarda o job "build" terminar

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./out

    - name: Build Docker image
      run: docker build -t grupo31/hackaton:latest -f out/Dockerfile .
    
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.HACKATON_DEPLOY_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/hackaton:latest
